-- Supabase admin dashboard setup
-- Run this in the Supabase SQL editor after the Auth user exists.

-- 1) Create the dashboard user in Supabase dashboard.
--    Authentication -> Users -> Add user
--    email: admin@gmail.com
--    password: Admin@123
--    If needed, disable email confirmation for local testing.

-- 2) Create the tables and RLS policies.
create extension if not exists pgcrypto;

create table if not exists public.projects (
  id bigint generated by default as identity primary key,
  title text not null,
  description text not null,
  image_url text default '../assets/images/profile.png',
  github_url text default '',
  live_url text default '',
  tags text[] not null default '{}',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.skills (
  id bigint generated by default as identity primary key,
  name text not null,
  level integer not null default 0 check (level between 0 and 100),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.services (
  id bigint generated by default as identity primary key,
  title text not null,
  description text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.testimonials (
  id bigint generated by default as identity primary key,
  name text not null,
  role text default '',
  quote text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.contact_messages (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null,
  subject text default 'General enquiry',
  message text not null,
  created_at timestamptz not null default now()
);

create or replace function public.set_updated_at()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

drop trigger if exists set_projects_updated_at on public.projects;
create trigger set_projects_updated_at
before update on public.projects
for each row
execute function public.set_updated_at();

drop trigger if exists set_skills_updated_at on public.skills;
create trigger set_skills_updated_at
before update on public.skills
for each row
execute function public.set_updated_at();

drop trigger if exists set_services_updated_at on public.services;
create trigger set_services_updated_at
before update on public.services
for each row
execute function public.set_updated_at();

drop trigger if exists set_testimonials_updated_at on public.testimonials;
create trigger set_testimonials_updated_at
before update on public.testimonials
for each row
execute function public.set_updated_at();

alter table public.projects enable row level security;
alter table public.skills enable row level security;
alter table public.services enable row level security;
alter table public.testimonials enable row level security;
alter table public.contact_messages enable row level security;

drop policy if exists "Public can read projects" on public.projects;
create policy "Public can read projects"
on public.projects
for select
using (true);

drop policy if exists "Authenticated users can manage projects" on public.projects;
create policy "Authenticated users can manage projects"
on public.projects
for all
using (auth.role() = 'authenticated')
with check (auth.role() = 'authenticated');

drop policy if exists "Public can read skills" on public.skills;
create policy "Public can read skills"
on public.skills
for select
using (true);

drop policy if exists "Authenticated users can manage skills" on public.skills;
create policy "Authenticated users can manage skills"
on public.skills
for all
using (auth.role() = 'authenticated')
with check (auth.role() = 'authenticated');

drop policy if exists "Public can read services" on public.services;
create policy "Public can read services"
on public.services
for select
using (true);

drop policy if exists "Authenticated users can manage services" on public.services;
create policy "Authenticated users can manage services"
on public.services
for all
using (auth.role() = 'authenticated')
with check (auth.role() = 'authenticated');

drop policy if exists "Public can read testimonials" on public.testimonials;
create policy "Public can read testimonials"
on public.testimonials
for select
using (true);

drop policy if exists "Authenticated users can manage testimonials" on public.testimonials;
create policy "Authenticated users can manage testimonials"
on public.testimonials
for all
using (auth.role() = 'authenticated')
with check (auth.role() = 'authenticated');

drop policy if exists "Anyone can create a contact message" on public.contact_messages;
create policy "Anyone can create a contact message"
on public.contact_messages
for insert
with check (true);

drop policy if exists "Authenticated users can read contact messages" on public.contact_messages;
create policy "Authenticated users can read contact messages"
on public.contact_messages
for select
using (auth.role() = 'authenticated');

drop policy if exists "Authenticated users can delete contact messages" on public.contact_messages;
create policy "Authenticated users can delete contact messages"
on public.contact_messages
for delete
using (auth.role() = 'authenticated');

create index if not exists idx_projects_created_at on public.projects (created_at desc);
create index if not exists idx_skills_name on public.skills (name);
create index if not exists idx_services_title on public.services (title);
create index if not exists idx_testimonials_name on public.testimonials (name);
create index if not exists idx_contact_messages_created_at on public.contact_messages (created_at desc);

-- 3) Seed starter content.
insert into public.projects (title, description, image_url, github_url, live_url, tags)
values
  ('Personal Portfolio', 'A modern, fully responsive portfolio website showcasing my skills, projects and services.', '../assets/images/profile.png', '#', '#', array['HTML', 'CSS', 'JavaScript']),
  ('Restaurant Website', 'An elegant restaurant site with menu, reservation form and online ordering layout.', '../assets/images/profile.png', '#', '#', array['HTML', 'CSS', 'JS', 'PHP']),
  ('Weather App', 'Real-time weather dashboard using a public API — search any city and get live conditions.', '../assets/images/profile.png', '#', '#', array['JavaScript', 'API', 'CSS'])
on conflict do nothing;

insert into public.skills (name, level)
values
  ('HTML & CSS', 90),
  ('JavaScript', 85),
  ('React', 80),
  ('Node.js', 75)
on conflict do nothing;

insert into public.services (title, description)
values
  ('Web Development', 'Complete website builds from scratch and front-end polish.'),
  ('UI/UX Design', 'Clean, user-first interfaces built for clarity and conversion.'),
  ('API Integration', 'Connect systems, data sources and third-party tools efficiently.')
on conflict do nothing;

insert into public.testimonials (name, role, quote)
values
  ('Jane Doe', 'Startup Founder', 'Joseph transformed our rough idea into a polished digital product people actually enjoy using.'),
  ('Michael Shaw', 'Marketing Lead', 'The communication, design quality and delivery speed were excellent throughout the project.')
on conflict do nothing;