-- Portfolio Supabase schema
-- Run this in the Supabase SQL editor after creating the dashboard admin account.
--
-- Authentication setup (required for the dashboard):
-- 1. Open Supabase Dashboard -> Authentication -> Users
-- 2. Add user with a valid email, for example admin@gmail.com
-- 3. Set a strong, unique password for the admin user.
-- 4. If email confirmation is enabled, disable it for local admin use or confirm the user.
--
-- This schema enables public reads for the portfolio pages and authenticated writes for the dashboard.

create extension if not exists pgcrypto;

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'project-images',
  'project-images',
  true,
  5242880,
  array['image/png', 'image/jpeg', 'image/webp', 'image/gif']
)
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "Public can read project images" on storage.objects;
create policy "Public can read project images"
on storage.objects
for select
using (bucket_id = 'project-images');

drop policy if exists "Authenticated users can upload project images" on storage.objects;
create policy "Authenticated users can upload project images"
on storage.objects
for insert
to authenticated
with check (
  bucket_id = 'project-images'
  and auth.uid() is not null
  and octet_length(name) > 0
  and octet_length(name) <= 255
);

drop policy if exists "Authenticated users can update project images" on storage.objects;
create policy "Authenticated users can update project images"
on storage.objects
for update
to authenticated
using (bucket_id = 'project-images' and auth.uid() is not null)
with check (bucket_id = 'project-images' and auth.uid() is not null);

drop policy if exists "Authenticated users can delete project images" on storage.objects;
create policy "Authenticated users can delete project images"
on storage.objects
for delete
to authenticated
using (bucket_id = 'project-images' and auth.uid() is not null);

create table if not exists public.projects (
  id bigint generated by default as identity primary key,
  title text not null,
  description text not null,
  image_url text default '../assets/images/profile.png',
  github_url text default '',
  live_url text default '',
  tags text[] not null default '{}',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.skills (
  id bigint generated by default as identity primary key,
  name text not null,
  level integer not null default 0 check (level between 0 and 100),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.services (
  id bigint generated by default as identity primary key,
  title text not null,
  description text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.testimonials (
  id bigint generated by default as identity primary key,
  name text not null,
  role text default '',
  quote text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.contact_messages (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null,
  subject text default 'General enquiry',
  message text not null,
  created_at timestamptz not null default now()
);

create or replace function public.set_updated_at()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

drop trigger if exists set_projects_updated_at on public.projects;
create trigger set_projects_updated_at
before update on public.projects
for each row
execute function public.set_updated_at();

drop trigger if exists set_skills_updated_at on public.skills;
create trigger set_skills_updated_at
before update on public.skills
for each row
execute function public.set_updated_at();

drop trigger if exists set_services_updated_at on public.services;
create trigger set_services_updated_at
before update on public.services
for each row
execute function public.set_updated_at();

drop trigger if exists set_testimonials_updated_at on public.testimonials;
create trigger set_testimonials_updated_at
before update on public.testimonials
for each row
execute function public.set_updated_at();

alter table public.projects enable row level security;
alter table public.skills enable row level security;
alter table public.services enable row level security;
alter table public.testimonials enable row level security;
alter table public.contact_messages enable row level security;

create policy "Public can read projects"
on public.projects
for select
using (true);

create policy "Authenticated users can manage projects"
on public.projects
for all
using (auth.role() = 'authenticated')
with check (auth.role() = 'authenticated');

create policy "Public can read skills"
on public.skills
for select
using (true);

create policy "Authenticated users can manage skills"
on public.skills
for all
using (auth.role() = 'authenticated')
with check (auth.role() = 'authenticated');

create policy "Public can read services"
on public.services
for select
using (true);

create policy "Authenticated users can manage services"
on public.services
for all
using (auth.role() = 'authenticated')
with check (auth.role() = 'authenticated');

create policy "Public can read testimonials"
on public.testimonials
for select
using (true);

create policy "Authenticated users can manage testimonials"
on public.testimonials
for all
using (auth.role() = 'authenticated')
with check (auth.role() = 'authenticated');

create policy "Anyone can create a contact message"
on public.contact_messages
for insert
with check (true);

create policy "Authenticated users can read contact messages"
on public.contact_messages
for select
using (auth.role() = 'authenticated');

create policy "Authenticated users can delete contact messages"
on public.contact_messages
for delete
using (auth.role() = 'authenticated');

create index if not exists idx_projects_created_at on public.projects (created_at desc);
create index if not exists idx_skills_name on public.skills (name);
create index if not exists idx_services_title on public.services (title);
create index if not exists idx_testimonials_name on public.testimonials (name);
create index if not exists idx_contact_messages_created_at on public.contact_messages (created_at desc);
